In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the passenger data
passengers = pd.read_csv('passengers.csv')

In [2]:
passengers.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
# Update sex column to numerical
passengers['Sex'] = passengers['Sex'].map({'male':0,'female':1})

In [4]:
# Fill the nan values in the age column
passengers['Age'].fillna(inplace = True,value=round(passengers['Age'].mean()))

In [5]:
# Create a first class column
passengers['FirstClass'] = passengers['Pclass'].apply(lambda p: 1 if p == 1 else 0) 

In [6]:
# Create a second class column
passengers['SecondClass'] = passengers['Pclass'].apply(lambda p: 1 if p == 2 else 0)

In [7]:
passengers.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  FirstClass  SecondClass  
0         A/5 21171   7.2500   NaN        S           0            0  
1          PC 17599  71.2833   C85        C           1            0  
2  STON/O2. 3101282   7.9250   NaN        S           0            0  
3            113803  53.1000  C123        S           1            0  
4            373450   8.0500   NaN        S           0            0

In [8]:
# Select the desired features
features = passengers[['Sex','Age','FirstClass','SecondClass']]
survived = passengers['Survived']

In [9]:
# Perform train, test, split
train_features, test_features, train_lables, test_lables = train_test_split(features, survived)

In [10]:
# Scale the feature data so it has mean = 0 and standard deviation = 1
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

C:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [11]:
train_features

array([[ 1.35740679,  0.43916434,  1.76015894, -0.51725447],
       [ 1.35740679,  0.05556756, -0.56813051, -0.51725447],
       [-0.73669883,  1.436516  , -0.56813051,  1.93328442],
       ...,
       [ 1.35740679,  0.05556756, -0.56813051, -0.51725447],
       [-0.73669883, -0.55818731,  1.76015894, -0.51725447],
       [ 1.35740679, -0.0211518 , -0.56813051,  1.93328442]])

In [12]:
# Create and train the model
model = LogisticRegression()
model.fit(train_features, train_lables)

C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
# Score the model on the train data
print(model.score(train_features,train_lables))

0.7994011976047904


In [14]:
# Score the model on the test data
print(model.score(test_features,test_lables))

0.8026905829596412


In [15]:
# Analyze the coefficients
print(model.coef_)
print(list(zip(['Sex','Age','FirstClass','SecondClass'],model.coef_[0])))


[[ 1.26699174 -0.4450583   0.99820661  0.49344055]]
[('Sex', 1.2669917370839032), ('Age', -0.4450583030443619), ('FirstClass', 0.9982066145696659), ('SecondClass', 0.4934405525565405)]


In [16]:
# Sample passenger features
Jack = np.array([0.0,20.0,0.0,0.0])
Rose = np.array([1.0,17.0,1.0,0.0])
You = np.array([0.0,24.0,0.0,1.0])

In [17]:
# Combine passenger arrays
sample_passengers = np.array([Jack,Rose,You])

In [18]:
# Scale the sample passenger features
sample_passenegrs = scaler.transform(sample_passengers)
print(sample_passengers)

[[ 0. 20.  0.  0.]
 [ 1. 17.  1.  0.]
 [ 0. 24.  0.  1.]]


In [19]:
# Make survival predictions!
print(model.predict(sample_passengers))

[0 0 0]


In [20]:
#according to the model, none survive in sample_passengers